Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"

    # Bat cham nhe vao touchpad
    Option "Tapping" "on"

    # Quy dinh thu tu cham: 1 ngon = Trai, 2 ngon = Phai, 3 ngon = Giua (Middle)
    Option "TappingButtonMap" "lrm"

    # Bam vat ly xuong touchpad: 1 ngon = Trai, 2 ngon = Phai, 3 ngon = Giua (Middle)
    Option "ClickMethod" "clickfinger"

    # Cuon tu nhien
    Option "NaturalScrolling" "true"

    # Cuon bang 2 ngon
    Option "ScrollMethod" "twofinger"

    # Giu ngon tay de keo tha
    Option "TappingDrag" "on"
EndSection
