;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #161616
background-alt = #282828
foreground = #C5C8C6
primary = #50a5f5
secondary = #52bdff
alert = #ebf831
disabled = #4e5b55
border = #0f2923

[bar/example]
monitor = ${env:MONITOR:}
width = 100%
height = 24pt
radius = 6

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 2
padding-right = 2

module-margin = 1

; font-0 = Roboto Mono Nerd Font:size=11:weight=medium;3
; font-1 = "JetBrainsMono Nerd Font:size=10"
font-0 = "JetBrainsMono Nerd Font:size=10;2"
font-1 = "Symbols Nerd Font:size=11;2"

modules-left = launcher sep xworkspaces
modules-center = xwindow
modules-right = sep date hour sep memory cpu sep lock input_method bluetooth wlan eth pulseaudio battery powermenu 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

;==========================================================;
[module/launcher]
type = custom/text
format = 
format-foreground = ${colors.primary}
format-padding = 0
click-left = xfce4-appfinder &

;==========================================================;
[module/sep]
type = custom/text
format = |
format-foreground = ${colors.disabled}

;==========================================================;
[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

;==========================================================;
[module/xwindow]
type = internal/xwindow
label = %title:0:75:...%

;==========================================================;
[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

;==========================================================;
[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = true
interval = 1

format-volume = <ramp-volume> <label-volume>
format-volume-foreground = ${colors.foreground}

label-volume = %percentage%%
label-volume-foreground = ${colors.foreground}

format-muted = <label-muted>
format-muted-prefix = "󰝟 "
format-muted-prefix-foreground = ${colors.disabled}
label-muted = "Muted"
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾
ramp-volume-foreground = ${colors.primary}

click-right = pavucontrol &

;==========================================================;
[module/battery]
type = internal/battery
full-at = 99
low-at = 15

battery = BAT1
adapter = ACAD
poll-interval = 5

format-charging = <animation-charging> <label-charging>
label-charging = %percentage%%
label-charging-foreground = ${colors.foreground}

format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
label-discharging-foreground = ${colors.foreground}

format-full-prefix = "  "
format-full-prefix-foreground = ${colors.primary}
label-full = %percentage%%

format-low = <animation-low> <label-low>
label-low = %percentage%%
label-low-foreground = ${colors.alert}

ramp-capacity-0 =  
ramp-capacity-1 =  
ramp-capacity-2 =  
ramp-capacity-3 =  
ramp-capacity-4 =  
ramp-capacity-foreground = ${colors.secondary}

animation-charging-0 =  
animation-charging-1 =  
animation-charging-2 =  
animation-charging-3 =  
animation-charging-4 =  
animation-charging-foreground = ${colors.secondary}
animation-charging-framerate = 750

animation-low-0 =  
animation-low-1 = "  "
animation-low-foreground = ${colors.alert}
animation-low-framerate = 500

;==========================================================;
[module/input_method]
type = custom/script
exec = zsh -c 'IM=$(fcitx5-remote -n); if [ "$IM" = "bamboo" ] || [ "$IM" = "unikey" ]; then echo "VN"; else echo "EN"; fi'
interval = 0.2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %output%
click-left = fcitx5-remote -t

;==========================================================;
[module/lock]
type = internal/xkeyboard
format-margin = 0
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-indicator>
label-indicator-padding = 0
indicator-icon-0 = caps lock;-CL;+CL
label-indicator-off =
label-indicator-on = "  Caps "
format-foreground = ${colors.background}
format-background = ${colors.alert}

;==========================================================;
[module/memory]
type = internal/memory
interval = 2
format = %{A1:alacritty --class "btop-term,btop-term" -e btop &:}RAM <label>%{A}
format-foreground = ${colors.primary}
label = %percentage_used:2%%
label-foreground = ${colors.foreground}

;==========================================================;
[module/cpu]
type = internal/cpu
interval = 2
format = %{A1:alacritty --class "btop-term,btop-term" -e htop &:}CPU <label>%{A}
format-foreground = ${colors.primary}
label = %percentage:2%%
label-foreground = ${colors.foreground}

;==========================================================;
[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

;==========================================================;
; [module/wlan]
; inherit = network-base; click-left = alacritty --class "float-term" -e nmtui &
; click-left = nm-connection-editor &

; interface-type = wireless
; label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

;==========================================================;
[module/wlan]
inherit = network-base
interface-type = wireless
interval = 3.0

; format-connected = %{A1:alacritty --class "float-term" -e nmtui &:}<ramp-signal> <label-connected>%{A}%{A}
format-connected = %{A1:nm-connection-editor &:}<ramp-signal> <label-connected>%{A}%{A}
label-connected = %essid%
label-connected-foreground = ${colors.foreground}

format-disconnected = %{A1:alacritty --class "float-term" -e nmtui &:}%{A3:nm-connection-editor &:}<label-disconnected>%{A}%{A}
format-disconnected-prefix = "󰤮 "
format-disconnected-prefix-foreground = ${colors.disabled}
label-disconnected = "Offline"
label-disconnected-foreground = ${colors.disabled}

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨
ramp-signal-foreground = ${colors.primary}

;==========================================================;
[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

;;;;;;;;;;;;;;;; CENTER MODULES ;;;;;;;;;;;;;;;;

;==========================================================;
[module/hour]
type = internal/date
interval = 5
label-foreground = ${colors.foreground}
date = %l:%M %p
label = %date%
label-padding = 0
label-font = 1

;==========================================================;
[module/date]
type = custom/script
interval = 5
format = <label>
exec = LC_TIME=en_US.UTF-8 date +"%a, %b %-d"
label-padding = 0
label-font = 1
click-left = gsimplecal

;==========================================================;
[module/screenshot]
type = custom/text
format = 󰻛
format-foreground = ${colors.secondary}
click-left = flameshot gui

;==========================================================;
[module/powermenu]
type = custom/text
format = 󰐥
format-foreground = ${colors.alert}
click-left = ~/.config/openbox/scripts/power

;==========================================================;
[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh
interval = 3
click-left = blueman-manager &
click-right = bash -c 'if [ "$(bluetoothctl show | grep -i "Powered: yes")" ]; then bluetoothctl power off; else bluetoothctl power on; fi'

;==========================================================;
[module/tray]
type = internal/tray
tray-spacing = 4px

[settings]
screenchange-reload = true
pseudo-transparency = true